name: CI

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.10", "=3.7[build=*_pypy]", "=3.8[build=*_pypy]"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # We need Python 3.7 to always be installed, so tests with
      # multiple environments can run.
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Setup Conda with ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install dependencies
        shell: bash -el {0}
        run: python -m pip install -r requirements-dev.txt

      - name: Get mamba
        shell: bash -el {0}
        run: conda install mamba -c conda-forge

      - name: Install asv
        shell: bash -el {0}
        run: pip install .

      - name: Run tests
        shell: bash -el {0}
        run: python -m pytest -v --timeout=300 --durations=20 test

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge

      - name: Get mamba
        shell: bash -el {0}
        run: conda install mamba -c conda-forge

      - name: Install dependencies
        shell: bash -el {0}
        run: python -m pip install -r requirements-dev.txt

      - name: Install asv
        shell: bash -el {0}
        run: pip install ".[doc]"

      - name: Build docs
        shell: bash -el {0}
        run: sphinx-build -W docs/source html
